os:
  - linux
language: android
android:
  components:
    - platform-tools
    - tools
    - build-tools-28.0.3
    - android-30
    - add-on
    - extra
  licenses:
    - 'android-sdk-license-.+'
jdk:
  - oraclejdk8
addons:
  apt:
    # Flutter depends on /usr/lib/x86_64-linux-gnu/libstdc++.so.6 version GLIBCXX_3.4.18
    sources:
      - ubuntu-toolchain-r-test # if we don't specify this, the libstdc++6 we get is the wrong version
    packages:
      - libstdc++6
      - fonts-droid
before_install:
  - yes | sdkmanager --update
before_script:
  - git clone https://github.com/flutter/flutter.git -b stable --depth 1
  - export PATH="$PATH:`pwd`/flutter/bin"
script:
  - flutter packages get
  - flutter precache
  - yes | flutter doctor --android-licenses
  - flutter doctor && flutter -v build apk
  #  - find -type f -name "*.apk"
  - mv ./build/app/outputs/apk/release/app-release.apk ./TravisCI-$(git describe --tags).apk
cache:
  directories:
    - $HOME/.pub-cache
#deploy:
#  cleanup: true
#  provider: releases
#  token: <encrypted token>
#  file: ./TravisCI-$(git describe --tags).apk
#  edge: true # opt in to dpl v2
#  on:
#    tags: true